[build]
builder = "dockerfile"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve -s dist -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 