[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

# Variables d'environnement pour Railway
[env]
VITE_SUPABASE_URL = "https://lqxfjjtjxktjgpekugtf.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeGZqanRqeGt0amdwZWt1Z3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTgyMDMsImV4cCI6MjA2MzM3NDIwM30.-E66kbBxRAVcJcPdhhUJWq5BZB-2GRpiBEaGtiWLVrA"
# IMPORTANT: Configurez MISTRAL_API_KEY dans le dashboard Railway !
# MISTRAL_API_KEY = "votre_vraie_cle_mistral_ici"

# Variables d'environnement requises pour le déploiement
# À configurer via l'interface Railway ou CLI
VITE_API_BASE_URL = "https://normal-trade-production.up.railway.app"
VITE_TRUELAYER_CLIENT_ID = ""  # À configurer
VITE_TRUELAYER_ENV = "sandbox"  # sandbox ou live 