[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install"

[deploy]
startCommand = "cd frontend && npm run build && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 