[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "gcc",
    "postgresql",
    "openssl"
]

[phases.install]
cmds = [
    "cd /app/backend && pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
    "cd /app/backend && chmod +x start.sh"
]

[start]
cmd = "cd /app/backend && ./start.sh"

[variables]
PYTHONPATH = "/app/backend"
PYTHON_VERSION = "3.11" 