[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "gcc",
    "postgresql",
    "openssl"
]

[phases.install]
cmds = [
    "cd /app/backend && pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
    "cd /app/backend && python -c \"from mistral_cgi_embeddings import load_embeddings; print('✅ Embeddings CGI chargés:', len(load_embeddings()))\"",
    "cd /app/backend && python -c \"from mistral_embeddings import search_similar_bofip_chunks; print('✅ Embeddings BOFiP disponibles')\""
]

[start]
cmd = "cd /app/backend && /opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"
PYTHON_VERSION = "3.11" 