name: Security Scans

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit trufflehog
      - name: Bandit - Static security analysis
        run: |
          bandit -r backend -f sarif -o bandit-report.sarif || true
      - name: Upload Bandit report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-report.sarif

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history for secret scanning
      - name: Run Trufflehog
        run: |
          trufflehog filesystem --no-update --fail --json . || true
