name: Upload Francis DMG to S3

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.0.0)"
        required: true
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-rc*"

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build desktop app
        run: |
          cd desktop-app
          npm ci --legacy-peer-deps
          npm run build # builds Electron app
          # Build professional drag-and-drop DMG
          npm install -g create-dmg
          cd ../../
          ./desktop-app/build-dmg.sh 1.0.0
          cd desktop-app

      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: |
            desktop-app/dist/Francis-1.0.0.dmg
            desktop-app/dist/Francis-1.0.0-arm64.dmg


      - name: Success message
        run: echo "DMG uploaded to GitHub Release. Users can download via your site. https://${{ secrets.DOMAIN }}/downloads/Francis-1.0.0.dmg"
